// <auto-generated />
using System;
using DataEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEntity.Migrations
{
    [DbContext(typeof(SkladContext))]
    [Migration("20251006081422_003")]
    partial class _003
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataEntity.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MernaJednotkaId")
                        .HasColumnType("int");

                    b.Property<int>("MnozDoPal")
                        .HasColumnType("int");

                    b.Property<int>("MnozPoj")
                        .HasColumnType("int");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaterialId");

                    b.HasIndex("MernaJednotkaId");

                    b.ToTable("Materialy");
                });

            modelBuilder.Entity("DataEntity.MernaJednotka", b =>
                {
                    b.Property<int>("MernaJednotkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MernaJednotkaId"));

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MernaJednotkaId");

                    b.ToTable("MernaJednotka");
                });

            modelBuilder.Entity("DataEntity.Material", b =>
                {
                    b.HasOne("DataEntity.MernaJednotka", "MernaJednotka")
                        .WithMany("Materialy")
                        .HasForeignKey("MernaJednotkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MernaJednotka");
                });

            modelBuilder.Entity("DataEntity.MernaJednotka", b =>
                {
                    b.Navigation("Materialy");
                });
#pragma warning restore 612, 618
        }
    }
}
